import './globals.css'
import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: 'Admin Dashboard',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (

    <ClerkProvider>
    <html lang="en">
      <div>
      <body className={"inter.className"}>
        {children}
        </body>
        </div>
    </html>
    </ClerkProvider>
  )
}
